/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/activity` | `/activity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/charts` | `/charts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/GetMood/[child_id]` | `/GetMood/[child_id]`, params: Router.UnknownInputParams & { child_id: string | number; } } | { pathname: `${'/(tabs)'}/child/[child_id]` | `/child/[child_id]`, params: Router.UnknownInputParams & { child_id: string | number; } } | { pathname: `${'/(tabs)'}/diet/[child_id]` | `/diet/[child_id]`, params: Router.UnknownInputParams & { child_id: string | number; } } | { pathname: `${'/(tabs)'}/diet/[child_id]/feed/[recipe_id]` | `/diet/[child_id]/feed/[recipe_id]`, params: Router.UnknownInputParams & { child_id: string | number;recipe_id: string | number; } } | { pathname: `${'/(tabs)'}/diet/[child_id]/feed` | `/diet/[child_id]/feed`, params: Router.UnknownInputParams & { child_id: string | number; } } | { pathname: `${'/(tabs)'}/diet/[child_id]/feed/custom` | `/diet/[child_id]/feed/custom`, params: Router.UnknownInputParams & { child_id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/activity` | `/activity`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/charts` | `/charts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(tabs)'}/GetMood/[child_id]` | `/GetMood/[child_id]`, params: Router.UnknownOutputParams & { child_id: string; } } | { pathname: `${'/(tabs)'}/child/[child_id]` | `/child/[child_id]`, params: Router.UnknownOutputParams & { child_id: string; } } | { pathname: `${'/(tabs)'}/diet/[child_id]` | `/diet/[child_id]`, params: Router.UnknownOutputParams & { child_id: string; } } | { pathname: `${'/(tabs)'}/diet/[child_id]/feed/[recipe_id]` | `/diet/[child_id]/feed/[recipe_id]`, params: Router.UnknownOutputParams & { child_id: string;recipe_id: string; } } | { pathname: `${'/(tabs)'}/diet/[child_id]/feed` | `/diet/[child_id]/feed`, params: Router.UnknownOutputParams & { child_id: string; } } | { pathname: `${'/(tabs)'}/diet/[child_id]/feed/custom` | `/diet/[child_id]/feed/custom`, params: Router.UnknownOutputParams & { child_id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/activity${`?${string}` | `#${string}` | ''}` | `/activity${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/charts${`?${string}` | `#${string}` | ''}` | `/charts${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/activity` | `/activity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/charts` | `/charts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | `/+not-found` | `${'/(tabs)'}/GetMood/${Router.SingleRoutePart<T>}` | `/GetMood/${Router.SingleRoutePart<T>}` | `${'/(tabs)'}/child/${Router.SingleRoutePart<T>}` | `/child/${Router.SingleRoutePart<T>}` | `${'/(tabs)'}/diet/${Router.SingleRoutePart<T>}` | `/diet/${Router.SingleRoutePart<T>}` | `${'/(tabs)'}/diet/${Router.SingleRoutePart<T>}/feed/${Router.SingleRoutePart<T>}` | `/diet/${Router.SingleRoutePart<T>}/feed/${Router.SingleRoutePart<T>}` | `${'/(tabs)'}/diet/${Router.SingleRoutePart<T>}/feed` | `/diet/${Router.SingleRoutePart<T>}/feed` | `${'/(tabs)'}/diet/${Router.SingleRoutePart<T>}/feed/custom` | `/diet/${Router.SingleRoutePart<T>}/feed/custom` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/GetMood/[child_id]` | `/GetMood/[child_id]`, params: Router.UnknownInputParams & { child_id: string | number; } } | { pathname: `${'/(tabs)'}/child/[child_id]` | `/child/[child_id]`, params: Router.UnknownInputParams & { child_id: string | number; } } | { pathname: `${'/(tabs)'}/diet/[child_id]` | `/diet/[child_id]`, params: Router.UnknownInputParams & { child_id: string | number; } } | { pathname: `${'/(tabs)'}/diet/[child_id]/feed/[recipe_id]` | `/diet/[child_id]/feed/[recipe_id]`, params: Router.UnknownInputParams & { child_id: string | number;recipe_id: string | number; } } | { pathname: `${'/(tabs)'}/diet/[child_id]/feed` | `/diet/[child_id]/feed`, params: Router.UnknownInputParams & { child_id: string | number; } } | { pathname: `${'/(tabs)'}/diet/[child_id]/feed/custom` | `/diet/[child_id]/feed/custom`, params: Router.UnknownInputParams & { child_id: string | number; } };
    }
  }
}
